# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(266, 276)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Title.setGeometry(QtCore.QRect(90, 10, 81, 41))
        self.lbl_Title.setText("")
        self.lbl_Title.setObjectName("lbl_Title")
        self.btn_NewGame = QtWidgets.QPushButton(self.centralwidget)
        self.btn_NewGame.setGeometry(QtCore.QRect(90, 90, 81, 31))
        self.btn_NewGame.setObjectName("btn_NewGame")
        self.btn_Help = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Help.setGeometry(QtCore.QRect(90, 140, 81, 31))
        self.btn_Help.setObjectName("btn_Help")
        self.btn_AboutMe = QtWidgets.QPushButton(self.centralwidget)
        self.btn_AboutMe.setGeometry(QtCore.QRect(90, 190, 81, 31))
        self.btn_AboutMe.setObjectName("btn_AboutMe")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_NewGame.setText(_translate("MainWindow", "CHƠI GAME"))
        self.btn_Help.setText(_translate("MainWindow", "HƯỚNG DẪN"))
        self.btn_AboutMe.setText(_translate("MainWindow", "VỀ CHÚNG TÔI"))
