# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menugame1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 317)
        MainWindow.setMinimumSize(QtCore.QSize(368, 317))
        MainWindow.setStyleSheet("color : rgb(255, 255, 255);\n"
"background-color: rgb(255, 195, 98);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 20, 211, 251))
        self.frame.setMinimumSize(QtCore.QSize(211, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 80, 91, 20))
        self.label.setMinimumSize(QtCore.QSize(71, 20))
        self.label.setStyleSheet("color: rgb(7, 7, 7);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.btn_Help = QtWidgets.QPushButton(self.frame)
        self.btn_Help.setGeometry(QtCore.QRect(60, 170, 91, 31))
        self.btn_Help.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_Help.setStyleSheet("background-color: rgb(119, 144, 255);")
        self.btn_Help.setObjectName("btn_Help")
        self.btn_NewGame = QtWidgets.QPushButton(self.frame)
        self.btn_NewGame.setGeometry(QtCore.QRect(60, 120, 91, 31))
        self.btn_NewGame.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_NewGame.setStyleSheet("background-color: rgb(119, 144, 255);")
        self.btn_NewGame.setObjectName("btn_NewGame")
        self.btn_AboutMe = QtWidgets.QPushButton(self.frame)
        self.btn_AboutMe.setGeometry(QtCore.QRect(60, 220, 91, 31))
        self.btn_AboutMe.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_AboutMe.setStyleSheet("background-color: rgb(119, 144, 255);")
        self.btn_AboutMe.setObjectName("btn_AboutMe")
        self.lbl_Img = QtWidgets.QLabel(self.frame)
        self.lbl_Img.setGeometry(QtCore.QRect(60, 10, 91, 71))
        self.lbl_Img.setMinimumSize(QtCore.QSize(91, 71))
        self.lbl_Img.setText("")
        self.lbl_Img.setPixmap(QtGui.QPixmap("D:/Python/ChessGame/Chess/Chess/design/img/logo.jpg"))
        self.lbl_Img.setScaledContents(True)
        self.lbl_Img.setObjectName("lbl_Img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  CHESS GAME"))
        self.btn_Help.setText(_translate("MainWindow", "HELP"))
        self.btn_NewGame.setText(_translate("MainWindow", "NEW GAME"))
        self.btn_AboutMe.setText(_translate("MainWindow", "ABOUT ME"))
