# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menugame2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowPlay(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(366, 317)
        MainWindow.setStyleSheet("background-color: rgb(255, 195, 98);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 20, 211, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 80, 91, 20))
        self.label.setStyleSheet("color: rgb(7, 7, 7);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.btn_TwoPlay = QtWidgets.QPushButton(self.frame)
        self.btn_TwoPlay.setGeometry(QtCore.QRect(60, 170, 91, 31))
        self.btn_TwoPlay.setStyleSheet("background-color: rgb(119, 144, 255);")
        self.btn_TwoPlay.setObjectName("btn_TwoPlay")
        self.btn_OnePlay = QtWidgets.QPushButton(self.frame)
        self.btn_OnePlay.setGeometry(QtCore.QRect(60, 120, 91, 31))
        self.btn_OnePlay.setStyleSheet("background-color: rgb(119, 144, 255);")
        self.btn_OnePlay.setObjectName("btn_OnePlay")
        self.lbl_Img = QtWidgets.QLabel(self.frame)
        self.lbl_Img.setGeometry(QtCore.QRect(60, 10, 91, 71))
        self.lbl_Img.setText("")
        self.lbl_Img.setPixmap(QtGui.QPixmap("D:/Python/ChessGame/Chess/Chess/design/img/logo.jpg"))
        self.lbl_Img.setScaledContents(True)
        self.lbl_Img.setObjectName("lbl_Img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  CHESS GAME"))
        self.btn_TwoPlay.setText(_translate("MainWindow", "TWO PLAYER"))
        self.btn_OnePlay.setText(_translate("MainWindow", "ONE PLAYER"))
